# Generated by Django 4.1.6 on 2023-02-02 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_work', models.CharField(default='director', max_length=15)),
                ('name', models.CharField(default='Test', max_length=20)),
                ('second_name', models.CharField(default='Testov', max_length=20)),
                ('sur_name', models.CharField(default='Testovich', max_length=20)),
                ('salary', models.IntegerField(default=10000)),
                ('dateStartWork', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Lead_Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_work', models.CharField(default='lead', max_length=15)),
                ('name', models.CharField(default='test', max_length=20)),
                ('second_name', models.CharField(default='testov', max_length=20)),
                ('sur_name', models.CharField(default='testovich', max_length=20)),
                ('salary', models.IntegerField(default=0)),
                ('dateStartWork', models.DateField()),
                ('pos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dbStructure.director')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_work', models.CharField(default='tester', max_length=15)),
                ('name', models.CharField(default='test', max_length=20)),
                ('second_name', models.CharField(default='testov', max_length=20)),
                ('sur_name', models.CharField(default='testovich', max_length=20)),
                ('salary', models.IntegerField(default=0)),
                ('dateStartWork', models.DateField()),
                ('pos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dbStructure.lead_department')),
            ],
        ),
    ]
